export const MAKE_REQUEST_ACTION = "MAKE_REQUEST_ACTION";

export const FAIL_REQUEST_ACTION = "FAIL_REQUEST_ACTION";

export const FETCH_CLIENTS_ACTION = "FETCH_CLIENTS_ACTION";

export const ADD_CLIENT_ACTION = "ADD_CLIENT_ACTION";

export const DELETE_CLIENT_ACTION = "DELETE_CLIENT_ACTION";

export const GET_SINGLE_CLIENT_ACTION = "GET_SINGLE_CLIENT_ACTION";

export const UPDATE_CLIENT_ACTION = "UPDATE_CLIENT_ACTION";
